/* global chrome, document, NodeFilter */
(()=>{
  const API_DEFAULT='https://livefy-tau.vercel.app/api/extension';
  const DASHBOARD_DEFAULT='https://livefy-tau.vercel.app/#settings';
  const CONSENT_VERSION='2026-08-17';
  const normalizeCode=value=>String(value||'').toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,16).replace(/(.{4})(?=.)/g,'$1-');
  const fnv1a=value=>{let hash=2166136261;for(const char of String(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(36)};
  const parseCount=value=>{const source=String(value||'').trim().toLowerCase().replace(/\s/g,'').replace(',','.');const match=source.match(/([\d.]+)([kmb]?)/);if(!match)return 0;const number=Number(match[1]);const multiplier={k:1e3,m:1e6,b:1e9}[match[2]]||1;return Number.isFinite(number)?Math.round(number*multiplier):0};
  const parsePrice=value=>{const source=String(value||'').replace(/[^\d,.]/g,'');if(!source)return 0;const comma=source.lastIndexOf(',');const dot=source.lastIndexOf('.');const decimal=comma>dot?',':'.';const normalized=source.replace(decimal==='.'?/,/g:/\./g,'').replace(decimal,'.');const number=Number(normalized);return Number.isFinite(number)?Math.max(0,number):0};
  const pageType=url=>{const value=String(url||'');if(/livecenter|live_center/i.test(value))return'live-center';if(/\/live\/?/i.test(value))return'live-room';return'tiktok'};
  const localizePage=()=>{if(!globalThis.chrome?.i18n||!globalThis.document)return;const messages={'Live Bridge':'liveBridge','Connect this browser':'connectTitle','Generate a pairing code in Livefy Settings.':'connectHint','Device name':'deviceName','Pairing code':'pairingCode','Data disclosure':'disclosureTitle','When enabled, Livefy reads visible TikTok LIVE comments, product cards, page status and audience counts, then sends them securely to your workspace. It never reads passwords, cookies, private messages or form entries.':'disclosureBody','I understand and allow this capture while the switch is on.':'consentText','Connect browser':'connectButton','Connected':'connected','Capture TikTok LIVE':'captureTitle','Visible comments, products and audience metrics':'captureDetail','Pending events':'pendingEvents','Retry connection':'retry','Disconnect this browser':'disconnect','Open Livefy':'openLivefy','Settings':'settings','Live Bridge settings':'settingsTitle','Connection endpoints':'endpointsTitle','Production defaults work for most installations. Only change these values for a trusted Livefy deployment.':'endpointsIntro','Bridge API':'bridgeApi','Livefy dashboard':'dashboard','Save settings':'saveSettings','Privacy and captured data':'privacyTitle','The extension only inspects visible TikTok LIVE comments, product cards, page type and audience count while capture is enabled. It does not access cookies, passwords, payment data, private messages, browsing history outside TikTok or typed form values.':'privacySummary','Read the complete privacy disclosure':'readPrivacy'};const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){const source=node.nodeValue?.trim();const key=source&&messages[source];const translated=key&&chrome.i18n.getMessage(key);if(translated)node.nodeValue=node.nodeValue.replace(source,translated)}};
  globalThis.LivefyBridge=Object.freeze({API_DEFAULT,DASHBOARD_DEFAULT,CONSENT_VERSION,normalizeCode,fnv1a,parseCount,parsePrice,pageType,localizePage});
})();
