export class AudioMixer{
  private context:AudioContext|null=null;private source:MediaElementAudioSourceNode|null=null;private mediaGain:GainNode|null=null;private master:GainNode|null=null;private destination:MediaStreamAudioDestinationNode|null=null;private microphone:MediaStream|null=null;private microphoneSource:MediaStreamAudioSourceNode|null=null;private microphoneGain:GainNode|null=null;
  async initialize(element:HTMLMediaElement){if(this.context)return;this.context=new AudioContext();this.source=this.context.createMediaElementSource(element);this.mediaGain=this.context.createGain();this.master=this.context.createGain();this.destination=this.context.createMediaStreamDestination();this.source.connect(this.mediaGain).connect(this.master);this.master.connect(this.destination);this.master.connect(this.context.destination)}
  async resume(){if(this.context?.state==='suspended')await this.context.resume()}
  get outputTrack(){return this.destination?.stream.getAudioTracks()[0]??null}setMediaVolume(value:number){if(this.mediaGain)this.mediaGain.gain.value=value}setMasterVolume(value:number){if(this.master)this.master.gain.value=value}setMuted(muted:boolean){if(this.master)this.master.gain.value=muted?0:1}
  async enableMicrophone(){if(!this.context)throw new Error('Audio mixer is not initialized.');this.microphone=await navigator.mediaDevices.getUserMedia({audio:true});this.microphoneSource=this.context.createMediaStreamSource(this.microphone);this.microphoneGain=this.context.createGain();this.microphoneSource.connect(this.microphoneGain).connect(this.master!)}
  setMicrophoneVolume(value:number){if(this.microphoneGain)this.microphoneGain.gain.value=value}muteMicrophone(muted:boolean){if(this.microphoneGain)this.microphoneGain.gain.value=muted?0:1}
  async destroy(){this.microphone?.getTracks().forEach(track=>track.stop());this.source?.disconnect();this.mediaGain?.disconnect();this.microphoneSource?.disconnect();this.microphoneGain?.disconnect();this.master?.disconnect();await this.context?.close();this.context=null}
}
