import type { Product } from '../livefy-data';import { AudioMixer } from './audio-mixer';import { BroadcastComposer } from './broadcast-composer';import { RuntimeEventBus } from './event-bus';import { PlaylistEngine,type PlaylistSnapshot } from './playlist-engine';import type { BroadcastDestination } from './destination';import { PRESETS,type BroadcastPreset,type BroadcastState,type ResolvedMedia } from './types';
type Events={'state':BroadcastState;'error':Error;'media:duration':{id:string;duration:number}};
export class BroadcastEngine{
 readonly events=new RuntimeEventBus<Events>();readonly playlist=new PlaylistEngine();readonly audio=new AudioMixer();readonly composer:BroadcastComposer;private stream:MediaStream|null=null;private destination:BroadcastDestination|null=null;private volume=1;private muted=false;private errors:string[]=[];private preset:BroadcastPreset='vertical';private unsubscribe:Array<()=>void>=[];
 constructor(){this.composer=new BroadcastComposer(this.playlist,this.preset);this.unsubscribe.push(this.playlist.events.on('state',state=>this.emit(state)),this.playlist.events.on('media:error',error=>this.fail(error)),this.playlist.events.on('media:duration',payload=>this.events.emit('media:duration',payload)))}
 async initialize(items:ResolvedMedia[]){await this.audio.initialize(this.playlist.element);this.playlist.load(items);this.composer.start();this.rebuildStream();this.emit(this.playlist.snapshot)}
 getOutputStream(){if(!this.stream)this.rebuildStream();return this.stream!}async attachDestination(destination:BroadcastDestination){this.destination=destination;await destination.connect(this.getOutputStream())}
 async play(){await this.audio.resume();await this.playlist.play()}pause(){this.playlist.pause()}stop(){this.playlist.stop()}next(){return this.playlist.next()}previous(){return this.playlist.previous()}seek(value:number){this.playlist.seek(value)}select(index:number){return this.playlist.select(index,true)}setVolume(value:number){this.volume=value;this.audio.setMediaVolume(value);this.emit(this.playlist.snapshot)}setMuted(value:boolean){this.muted=value;this.audio.setMuted(value);this.emit(this.playlist.snapshot)}setLoopPlaylist(value:boolean){this.playlist.setLoopPlaylist(value)}setLoopItem(value:boolean){this.playlist.setLoopItem(value)}setProduct(product:Product|null){this.composer.setProduct(product)}setText(text:string){this.composer.setText(text)}
 setPreset(preset:BroadcastPreset){this.preset=preset;this.composer.setPreset(preset);this.rebuildStream();this.emit(this.playlist.snapshot)}
 async destroy(){this.unsubscribe.forEach(fn=>fn());await this.destination?.disconnect();this.stream?.getTracks().forEach(track=>track.stop());this.composer.stop();this.playlist.destroy();await this.audio.destroy();this.events.clear()}
 private rebuildStream(){this.stream?.getVideoTracks().forEach(track=>track.stop());const canvasStream=this.composer.captureStream();const tracks=[...canvasStream.getVideoTracks()];const audioTrack=this.audio.outputTrack;if(audioTrack)tracks.push(audioTrack);this.stream=new MediaStream(tracks);if(this.destination)void this.destination.connect(this.stream)}
 private emit(snapshot:PlaylistSnapshot){const size=PRESETS[this.preset];this.events.emit('state',{items:snapshot.items,status:snapshot.status,current:snapshot.items[snapshot.index]??null,next:snapshot.items[snapshot.index+1]??(snapshot.loopPlaylist?snapshot.items[0]??null:null),currentTime:snapshot.currentTime,duration:snapshot.duration,volume:this.volume,muted:this.muted,loopPlaylist:snapshot.loopPlaylist,loopItem:snapshot.loopItem,resolution:size,fps:this.composer.fps,videoTrack:Boolean(this.stream?.getVideoTracks().some(track=>track.readyState==='live')),audioTrack:Boolean(this.stream?.getAudioTracks().some(track=>track.readyState==='live')),errors:[...this.errors]})}
 private fail(error:Error){this.errors=[error.message,...this.errors].slice(0,5);this.events.emit('error',error);this.emit(this.playlist.snapshot)}
}
