import type { PlaylistEngine } from './playlist-engine';
import { PRESETS,type BroadcastPreset,type SceneLayer } from './types';

export class BroadcastComposer{
  readonly canvas=document.createElement('canvas');private context=this.canvas.getContext('2d',{alpha:false})!;private layers:SceneLayer[]=[];private frame=0;private running=false;private camera:MediaStream|null=null;private cameraVideo=document.createElement('video');fps=30;
  constructor(private playlist:PlaylistEngine,preset:BroadcastPreset='vertical'){this.setPreset(preset);this.cameraVideo.muted=true;this.cameraVideo.playsInline=true}
  setPreset(preset:BroadcastPreset){const size=PRESETS[preset];this.canvas.width=size.width;this.canvas.height=size.height}setLayers(layers:SceneLayer[]){this.layers=[...layers].sort((a,b)=>a.zIndex-b.zIndex)}
  setProduct(product:SceneLayer['product']){this.layers=this.layers.filter(layer=>layer.type!=='product');if(product)this.layers.push({id:'product',type:'product',x:.06,y:.79,width:.88,height:.14,scale:1,zIndex:50,visible:true,opacity:1,product})}
  setText(text:string){this.layers=this.layers.filter(layer=>layer.type!=='text');if(text)this.layers.push({id:'text',type:'text',x:.06,y:.07,width:.88,height:.1,scale:1,zIndex:40,visible:true,opacity:1,text})}
  async enableCamera(){this.camera=await navigator.mediaDevices.getUserMedia({video:true});this.cameraVideo.srcObject=this.camera;await this.cameraVideo.play();this.layers.push({id:'camera',type:'camera',x:.68,y:.04,width:.27,height:.22,scale:1,zIndex:30,visible:true,opacity:1})}
  start(){if(this.running)return;this.running=true;const render=()=>{this.draw();if(this.running)this.frame=requestAnimationFrame(render)};render()}stop(){this.running=false;cancelAnimationFrame(this.frame);this.camera?.getTracks().forEach(track=>track.stop());this.camera=null}
  captureStream(){return this.canvas.captureStream(this.fps)}
  private draw(){const{width:w,height:h}=this.canvas;this.context.fillStyle='#101216';this.context.fillRect(0,0,w,h);const media=this.playlist.visualSource;if(media)this.cover(media,0,0,w,h);for(const layer of [...this.layers].sort((a,b)=>a.zIndex-b.zIndex)){if(!layer.visible)continue;this.context.save();this.context.globalAlpha=layer.opacity;const x=layer.x*w,y=layer.y*h,lw=layer.width*w*layer.scale,lh=layer.height*h*layer.scale;if(layer.type==='camera'&&this.cameraVideo.readyState>=2)this.cover(this.cameraVideo,x,y,lw,lh);if(layer.type==='image'&&layer.source)this.context.drawImage(layer.source,x,y,lw,lh);if(layer.type==='text'&&layer.text)this.drawText(layer.text,x,y,lw,lh);if(layer.type==='product'&&layer.product)this.drawProduct(layer.product.name,`${layer.product.currency} ${Number(layer.product.price).toFixed(2)}`,x,y,lw,lh);this.context.restore()}}
  private cover(source:CanvasImageSource,x:number,y:number,w:number,h:number){const sw=source instanceof HTMLVideoElement?source.videoWidth:source instanceof HTMLImageElement?source.naturalWidth:w;const sh=source instanceof HTMLVideoElement?source.videoHeight:source instanceof HTMLImageElement?source.naturalHeight:h;const scale=Math.max(w/(sw||w),h/(sh||h)),dw=(sw||w)*scale,dh=(sh||h)*scale;this.context.drawImage(source,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
  private drawText(text:string,x:number,y:number,w:number,h:number){this.context.fillStyle='rgba(15,17,20,.72)';this.context.fillRect(x,y,w,h);this.context.fillStyle='#fff';this.context.font=`700 ${Math.max(30,h*.34)}px sans-serif`;this.context.textBaseline='middle';this.context.fillText(text,x+h*.25,y+h/2,w-h*.5)}
  private drawProduct(name:string,price:string,x:number,y:number,w:number,h:number){this.context.fillStyle='rgba(248,249,250,.94)';this.roundRect(x,y,w,h,h*.12);this.context.fill();this.context.fillStyle='#17191d';this.context.font=`700 ${h*.22}px sans-serif`;this.context.fillText(name,x+h*.23,y+h*.42,w-h*.46);this.context.fillStyle='#246b5b';this.context.font=`700 ${h*.25}px sans-serif`;this.context.fillText(price,x+h*.23,y+h*.73,w-h*.46)}
  private roundRect(x:number,y:number,w:number,h:number,r:number){this.context.beginPath();this.context.roundRect(x,y,w,h,r)}
}
