#include <sddl.h>
#include "LivefyDirectShow.h"

namespace{constexpr LONG Width=1080,Height=1920,Fps=30;constexpr DWORD NV12Bytes=Width*Height*3/2;constexpr REFERENCE_TIME FrameDuration=10000000/Fps;constexpr wchar_t PipeName[]=L"\\\\.\\pipe\\livefy-camera-frames-v1";constexpr DWORD HeaderBytes=40;uint32_t U32(const BYTE* p){return p[0]|(p[1]<<8)|(p[2]<<16)|(p[3]<<24);}}

LivefyFrameReader::LivefyFrameReader(){Placeholder();m_thread=std::thread(&LivefyFrameReader::Run,this);}
LivefyFrameReader::~LivefyFrameReader(){m_stopping=true;if(m_thread.joinable())m_thread.join();}
void LivefyFrameReader::Placeholder(){const size_t y=Width*Height;m_latest.assign(NV12Bytes,128);std::fill(m_latest.begin(),m_latest.begin()+y,16);}
void LivefyFrameReader::CopyNV12(BYTE* destination,size_t length){std::lock_guard<std::mutex>lock(m_mutex);memcpy(destination,m_latest.data(),std::min(length,m_latest.size()));}
bool LivefyFrameReader::ReadExact(HANDLE pipe,void* destination,DWORD length){BYTE* cursor=static_cast<BYTE*>(destination);DWORD total=0;while(total<length&&!m_stopping){DWORD read=0;if(ReadFile(pipe,cursor+total,length-total,&read,nullptr)&&read){total+=read;continue;}if(GetLastError()==ERROR_NO_DATA){Sleep(2);continue;}return false;}return total==length;}
void LivefyFrameReader::Run(){while(!m_stopping){PSECURITY_DESCRIPTOR descriptor=nullptr;SECURITY_ATTRIBUTES security{sizeof(security),nullptr,FALSE};if(ConvertStringSecurityDescriptorToSecurityDescriptorW(L"D:(A;;GRGW;;;AU)(A;;GA;;;SY)(A;;GA;;;BA)",SDDL_REVISION_1,&descriptor,nullptr))security.lpSecurityDescriptor=descriptor;HANDLE pipe=CreateNamedPipeW(PipeName,PIPE_ACCESS_INBOUND,PIPE_TYPE_BYTE|PIPE_READMODE_BYTE|PIPE_NOWAIT,1,0,4*1024*1024,0,security.lpSecurityDescriptor?&security:nullptr);if(descriptor)LocalFree(descriptor);if(pipe==INVALID_HANDLE_VALUE){Sleep(500);continue;}while(!m_stopping){if(ConnectNamedPipe(pipe,nullptr)||GetLastError()==ERROR_PIPE_CONNECTED){m_connected=true;break;}if(GetLastError()!=ERROR_PIPE_LISTENING)break;Sleep(50);}while(!m_stopping&&m_connected){BYTE header[HeaderBytes]{};if(!ReadExact(pipe,header,HeaderBytes))break;if(memcmp(header,"LFNV",4)||header[4]!=1||U32(header+8)!=Width||U32(header+12)!=Height||U32(header+20)!=NV12Bytes)break;std::vector<BYTE>next(NV12Bytes);if(!ReadExact(pipe,next.data(),NV12Bytes))break;std::lock_guard<std::mutex>lock(m_mutex);m_latest.swap(next);}m_connected=false;DisconnectNamedPipe(pipe);CloseHandle(pipe);}}

LivefyCameraStream::LivefyCameraStream(HRESULT* result,CSource* filter):CSourceStream(NAME("Livefy Camera Capture"),result,filter,L"Capture"){}
STDMETHODIMP LivefyCameraStream::NonDelegatingQueryInterface(REFIID iid,void** object){if(iid==IID_IAMStreamConfig)return GetInterface(static_cast<IAMStreamConfig*>(this),object);if(iid==IID_IKsPropertySet)return GetInterface(static_cast<IKsPropertySet*>(this),object);return CSourceStream::NonDelegatingQueryInterface(iid,object);}
HRESULT LivefyCameraStream::BuildMediaType(bool nv12,CMediaType* mt){VIDEOINFOHEADER* vih=reinterpret_cast<VIDEOINFOHEADER*>(mt->AllocFormatBuffer(sizeof(VIDEOINFOHEADER)));if(!vih)return E_OUTOFMEMORY;ZeroMemory(vih,sizeof(*vih));vih->AvgTimePerFrame=FrameDuration;vih->bmiHeader.biSize=sizeof(BITMAPINFOHEADER);vih->bmiHeader.biWidth=Width;vih->bmiHeader.biHeight=Height;vih->bmiHeader.biPlanes=1;vih->bmiHeader.biBitCount=nv12?12:16;vih->bmiHeader.biCompression=nv12?MAKEFOURCC('N','V','1','2'):MAKEFOURCC('Y','U','Y','2');vih->bmiHeader.biSizeImage=nv12?NV12Bytes:Width*Height*2;mt->SetType(&MEDIATYPE_Video);mt->SetSubtype(nv12?&MEDIASUBTYPE_NV12:&MEDIASUBTYPE_YUY2);mt->SetFormatType(&FORMAT_VideoInfo);mt->SetTemporalCompression(FALSE);mt->SetSampleSize(vih->bmiHeader.biSizeImage);return S_OK;}
HRESULT LivefyCameraStream::GetMediaType(int position,CMediaType* mt){if(position<0)return E_INVALIDARG;if(position>1)return VFW_S_NO_MORE_ITEMS;return BuildMediaType(position==0,mt);}
HRESULT LivefyCameraStream::CheckMediaType(const CMediaType* mt){if(*mt->Type()!=MEDIATYPE_Video||(*mt->Subtype()!=MEDIASUBTYPE_NV12&&*mt->Subtype()!=MEDIASUBTYPE_YUY2)||*mt->FormatType()!=FORMAT_VideoInfo)return E_INVALIDARG;auto* vih=reinterpret_cast<VIDEOINFOHEADER*>(mt->Format());return vih&&vih->bmiHeader.biWidth==Width&&abs(vih->bmiHeader.biHeight)==Height?S_OK:E_INVALIDARG;}
HRESULT LivefyCameraStream::DecideBufferSize(IMemAllocator* allocator,ALLOCATOR_PROPERTIES* request){auto* vih=reinterpret_cast<VIDEOINFOHEADER*>(m_mt.Format());request->cBuffers=3;request->cbBuffer=vih->bmiHeader.biSizeImage;ALLOCATOR_PROPERTIES actual{};HRESULT hr=allocator->SetProperties(request,&actual);return SUCCEEDED(hr)&&actual.cbBuffer>=request->cbBuffer?S_OK:E_FAIL;}
void LivefyCameraStream::NV12ToYUY2(const BYTE* source,BYTE* destination){const BYTE* uv=source+Width*Height;for(LONG y=0;y<Height;y++){const BYTE* row=source+y*Width;const BYTE* chroma=uv+(y/2)*Width;BYTE* out=destination+y*Width*2;for(LONG x=0;x<Width;x+=2){*out++=row[x];*out++=chroma[x];*out++=row[x+1];*out++=chroma[x+1];}}}
HRESULT LivefyCameraStream::FillBuffer(IMediaSample* sample){if(!m_nextTick)m_nextTick=GetTickCount64();ULONGLONG now=GetTickCount64();if(now<m_nextTick)Sleep(static_cast<DWORD>(m_nextTick-now));m_nextTick+=1000/Fps;BYTE* output=nullptr;sample->GetPointer(&output);std::vector<BYTE>frame(NV12Bytes);m_reader.CopyNV12(frame.data(),frame.size());if(*m_mt.Subtype()==MEDIASUBTYPE_NV12)memcpy(output,frame.data(),NV12Bytes);else NV12ToYUY2(frame.data(),output);REFERENCE_TIME stop=m_sampleTime+FrameDuration;sample->SetTime(&m_sampleTime,&stop);m_sampleTime=stop;sample->SetActualDataLength(*m_mt.Subtype()==MEDIASUBTYPE_NV12?NV12Bytes:Width*Height*2);sample->SetSyncPoint(TRUE);return S_OK;}
STDMETHODIMP LivefyCameraStream::SetFormat(AM_MEDIA_TYPE* mt){if(!mt)return E_POINTER;CMediaType candidate(*mt);if(FAILED(CheckMediaType(&candidate)))return E_INVALIDARG;CAutoLock lock(&m_state);m_mt=candidate;return S_OK;}
STDMETHODIMP LivefyCameraStream::GetFormat(AM_MEDIA_TYPE** mt){if(!mt)return E_POINTER;CMediaType current;if(m_mt.IsValid())current=m_mt;else BuildMediaType(true,&current);*mt=CreateMediaType(&current);return *mt?S_OK:E_OUTOFMEMORY;}
STDMETHODIMP LivefyCameraStream::GetNumberOfCapabilities(int* count,int* size){if(!count||!size)return E_POINTER;*count=2;*size=sizeof(VIDEO_STREAM_CONFIG_CAPS);return S_OK;}
STDMETHODIMP LivefyCameraStream::GetStreamCaps(int index,AM_MEDIA_TYPE** mt,BYTE* caps){if(!mt||!caps)return E_POINTER;if(index<0||index>1)return S_FALSE;CMediaType type;BuildMediaType(index==0,&type);*mt=CreateMediaType(&type);if(!*mt)return E_OUTOFMEMORY;auto* config=reinterpret_cast<VIDEO_STREAM_CONFIG_CAPS*>(caps);ZeroMemory(config,sizeof(*config));config->guid=FORMAT_VideoInfo;config->InputSize.cx=Width;config->InputSize.cy=Height;config->MinOutputSize.cx=Width;config->MinOutputSize.cy=Height;config->MaxOutputSize.cx=Width;config->MaxOutputSize.cy=Height;config->MinFrameInterval=config->MaxFrameInterval=FrameDuration;config->MinBitsPerSecond=config->MaxBitsPerSecond=Width*Height*(index==0?12:16)*Fps;return S_OK;}
STDMETHODIMP LivefyCameraStream::Get(REFGUID set,DWORD id,LPVOID,DWORD,LPVOID data,DWORD length,DWORD* returned){if(set!=AMPROPSETID_Pin||id!=AMPROPERTY_PIN_CATEGORY)return E_PROP_SET_UNSUPPORTED;if(returned)*returned=sizeof(GUID);if(!data)return S_OK;if(length<sizeof(GUID))return E_UNEXPECTED;*reinterpret_cast<GUID*>(data)=PIN_CATEGORY_CAPTURE;return S_OK;}
STDMETHODIMP LivefyCameraStream::QuerySupported(REFGUID set,DWORD id,DWORD* support){if(!support)return E_POINTER;if(set==AMPROPSETID_Pin&&id==AMPROPERTY_PIN_CATEGORY){*support=KSPROPERTY_SUPPORT_GET;return S_OK;}return E_PROP_SET_UNSUPPORTED;}
LivefyCameraFilter::LivefyCameraFilter(IUnknown* outer,HRESULT* result):CSource(NAME("Livefy Camera"),outer,CLSID_LivefyCameraDirectShow){m_stream=new LivefyCameraStream(result,this);}
LivefyCameraFilter::~LivefyCameraFilter(){delete m_stream;m_stream=nullptr;}
CUnknown* WINAPI LivefyCameraFilter::CreateInstance(IUnknown* outer,HRESULT* result){auto* filter=new LivefyCameraFilter(outer,result);if(!filter&&result)*result=E_OUTOFMEMORY;return filter;}
