import assert from'node:assert/strict';
import test from'node:test';
import{LivefyAgent}from'./agent.js';
import type{MediaCache}from'./media-cache.js';
import type{MediaEngine}from'./media-engine.js';

test('PREPARE_SESSION caches authorized media, loads playlist and starts playback',async()=>{const loaded:unknown[]=[];let session='';const media={cameraProbe:{refresh:async()=>({installed:true,registered:true})},setSession:(value:string)=>{session=value},loadPlaylist:async(items:unknown[])=>{loaded.push(...items)},play:async()=>{},getState:()=>({state:'playing',mediaId:'media-1',positionMs:0,durationMs:1000,absolutePositionMs:0,loopIndex:0,volume:1,responseAudioPlaying:false,sessionId:session}),getVirtualCameraState:()=>({installed:true,registered:true})};const cache={resolve:async({mediaId}:{mediaId:string})=>({localPath:`C:\\cache\\${mediaId}.media`})};const agent=new LivefyAgent(media as unknown as MediaEngine,cache as unknown as MediaCache);const response=await agent.handle({id:'prepare-1',type:'PREPARE_SESSION',payload:{sessionId:'session-1',workspaceId:'workspace-1',playlist:[{mediaId:'media-1',signedUrl:'https://example.test/signed'}]}});assert.equal(response.ok,true);assert.equal(session,'session-1');assert.equal(loaded.length,1);if(response.ok){const payload=response.payload as{preparation:{state:string}};assert.equal(payload.preparation.state,'ready')}});

test('PREPARE_SESSION stops before download when camera is unavailable',async()=>{let downloaded=false;const media={cameraProbe:{refresh:async()=>({installed:false,registered:false})}};const cache={resolve:async()=>{downloaded=true;return{localPath:''}}};const agent=new LivefyAgent(media as unknown as MediaEngine,cache as unknown as MediaCache);const response=await agent.handle({id:'prepare-2',type:'PREPARE_SESSION',payload:{sessionId:'session-1',workspaceId:'workspace-1',playlist:[{mediaId:'media-1',signedUrl:'https://example.test/signed'}]}});assert.equal(response.ok,false);assert.equal(downloaded,false)});
