import { useEffect,useRef,useState,type ReactNode } from 'react';
import * as Icon from '../../icons';
import { Button,PageHeader,Section,Skeleton,Status } from '../../components';
import { useI18n } from '../../i18n';
import { useLivefyData,type MediaItem } from '../../livefy-data';
import { supabase } from '../../lib/supabase';
import { BroadcastEngine } from '../../broadcast/broadcast-engine';
import { DebugDestination } from '../../broadcast/destination';
import { mediaKind,type BroadcastPreset,type BroadcastState,type ResolvedMedia,type RuntimeStatus } from '../../broadcast/types';
import { AgentBridge,type AgentDiagnostics,type ExtensionWebState,type PreparationState } from '../../agent-bridge';

const initialState:BroadcastState={items:[],status:'idle',current:null,next:null,currentTime:0,duration:0,volume:1,muted:false,loopPlaylist:true,loopItem:false,resolution:{width:1080,height:1920},fps:30,videoTrack:false,audioTrack:false,errors:[]};
const formatTime=(value:number)=>{const safe=Number.isFinite(value)?Math.max(value,0):0;return`${String(Math.floor(safe/60)).padStart(2,'0')}:${String(Math.floor(safe%60)).padStart(2,'0')}`};
const statusTone=(status:RuntimeStatus)=>status==='playing'?'online':status==='error'?'error':status==='paused'?'paused':'neutral';

export default function BroadcastStudio(){
 const{media,products,sessions,workspace,loading,refresh}=useLivefyData();const{t}=useI18n();
 const canvasMount=useRef<HTMLDivElement>(null);const debugVideo=useRef<HTMLVideoElement>(null);const engineRef=useRef<BroadcastEngine|null>(null);
 const bridgeRef=useRef<AgentBridge|null>(null);const[state,setState]=useState(initialState);const[preparing,setPreparing]=useState(true);const[error,setError]=useState('');const[preset,setPreset]=useState<BroadcastPreset>('vertical');const[productId,setProductId]=useState('');const[text,setText]=useState('');const[livePreparing,setLivePreparing]=useState(false);const[preparation,setPreparation]=useState<PreparationState>('idle');const[agent,setAgent]=useState<AgentDiagnostics|null>(null);const[extension,setExtension]=useState<ExtensionWebState|null>(null);
 useEffect(()=>{let alive=true;let renewal=0;const engine=new BroadcastEngine();engineRef.current=engine;const offState=engine.events.on('state',setState);const offError=engine.events.on('error',failure=>setError(failure.message));const offDuration=engine.events.on('media:duration',({id,duration})=>{void supabase.from('media_items').update({duration_seconds:duration}).eq('id',id)});
  const start=async()=>{try{const resolved=await resolveMedia(media);if(!alive)return;await engine.initialize(resolved);engine.composer.canvas.className='broadcast-canvas';canvasMount.current?.append(engine.composer.canvas);if(debugVideo.current)await engine.attachDestination(new DebugDestination(debugVideo.current));renewal=window.setInterval(()=>void resolveMedia(media).then(items=>engine.playlist.load(items)).catch(failure=>setError(failure instanceof Error?failure.message:t('Signed media URLs could not be renewed.'))),50*60_000)}catch(failure){setError(failure instanceof Error?failure.message:t('Could not initialize Broadcast Core.'))}finally{if(alive)setPreparing(false)}};void start();return()=>{alive=false;clearInterval(renewal);engine.composer.canvas.remove();offState();offError();offDuration();void engine.destroy();engineRef.current=null}},[media,t]);
 useEffect(()=>{const bridge=new AgentBridge();bridgeRef.current=bridge;let active=true;let timer=0;const poll=async()=>{try{const[diagnostics,webState]=await Promise.all([bridge.command<AgentDiagnostics>('GET_AGENT_STATUS'),bridge.extensionState()]);if(active){setAgent(diagnostics);setExtension(webState);setPreparation(diagnostics.preparation?.state??'idle');setError(current=>isAgentUnavailableError(current)?'':current)}}catch(failure){if(active){setAgent(null);setExtension(null);setError(current=>current||friendlyError(failure))}}finally{if(active)timer=window.setTimeout(poll,1500)}};void poll();return()=>{active=false;clearTimeout(timer);bridge.destroy();bridgeRef.current=null}},[]);
 const prepareLive=async()=>{if(!bridgeRef.current||!workspace||!media.length)return;let runtimeSessionId='';setLivePreparing(true);setError('');setPreparation('checking_camera');try{let session=sessions.find(item=>item.status==='draft');if(!session){const created=await supabase.from('live_sessions').insert({workspace_id:workspace.id,title:'Livefy · '+new Date().toLocaleDateString(),platform:'tiktok',mode:'shop',status:'draft'}).select('*').single();if(created.error)throw created.error;session=created.data}runtimeSessionId=session!.id;await supabase.from('live_sessions').update({runtime_state:'preparing_media',runtime_error:null,runtime_updated_at:new Date().toISOString()}).eq('id',runtimeSessionId);const playlist=await Promise.all(media.map(async item=>{const signed=await supabase.storage.from('media').createSignedUrl(item.storage_path,3600);if(signed.error)throw signed.error;return{mediaId:item.id,playlistItemId:item.id,name:item.name,position:item.position,signedUrl:signed.data.signedUrl}}));const result=await bridgeRef.current.command<{preparation:AgentDiagnostics['preparation']}>('PREPARE_SESSION',{sessionId:runtimeSessionId,workspaceId:workspace.id,playlist},180000);setPreparation(result.preparation.state);setAgent(await bridgeRef.current.command<AgentDiagnostics>('GET_AGENT_STATUS'));await supabase.from('live_sessions').update({runtime_state:'ready',runtime_error:null,runtime_updated_at:new Date().toISOString()}).eq('id',runtimeSessionId)}catch(failure){const message=friendlyError(failure);setPreparation('error');setError(message);if(runtimeSessionId)await supabase.from('live_sessions').update({runtime_state:'error',runtime_error:message,runtime_updated_at:new Date().toISOString()}).eq('id',runtimeSessionId)}finally{setLivePreparing(false)}};
 const command=async(type:'PLAY'|'PAUSE'|'STOP'|'NEXT'|'PREVIOUS'|'SEEK'|'SET_VOLUME',payload:Record<string,unknown>={},preview?:()=>void)=>{try{if(!bridgeRef.current)throw new Error('Agent offline');const playback=await bridgeRef.current.command<AgentDiagnostics['playback']>(type,payload);setAgent(current=>current?{...current,playback}:current);preview?.()}catch(failure){setError(friendlyError(failure))}};
 const persistOrder=async(items:ResolvedMedia[])=>{const results=await Promise.all(items.map((item,position)=>supabase.from('media_items').update({position}).eq('id',item.id)));const failure=results.find(result=>result.error)?.error;if(failure)setError(failure.message)};
 const move=(index:number,direction:-1|1)=>{const engine=engineRef.current;if(!engine)return;engine.playlist.reorder(index,index+direction);void persistOrder(engine.playlist.snapshot.items)};
 const remove=async(index:number)=>{const engine=engineRef.current,item=state.items[index];if(!engine||!item)return;engine.playlist.remove(index);const result=await supabase.from('media_items').update({status:'archived'}).eq('id',item.id);if(result.error){setError(result.error.message);await refresh()}else await persistOrder(engine.playlist.snapshot.items)};
 const chooseProduct=(id:string)=>{setProductId(id);engineRef.current?.setProduct(products.find(product=>product.id===id)??null)};const choosePreset=(value:BroadcastPreset)=>{setPreset(value);engineRef.current?.setPreset(value)};const hasMedia=Boolean(state.current),liveReady=preparation==='ready',isPlaying=liveReady?agent?.playback.state==='playing':state.status==='playing';const position=liveReady?(agent?.playback.positionMs??0)/1000:state.currentTime;const duration=liveReady?(agent?.playback.durationMs??0)/1000:state.duration;
 return <div className="page wide broadcast-studio">
  <PageHeader eyebrow={t('Broadcast Core')} title={t('Broadcast Studio')} description={t('Compose and play private media as a browser-generated audiovisual stream.')} actions={<><Status label={liveReady?'LIVE local pronta':agent?'Agent conectado':'Agent offline'} tone={liveReady?'online':agent?'warning':'error'}/><Button kind="primary" icon={<Icon.Broadcast/>} disabled={preparing||livePreparing||!hasMedia||!workspace} onClick={()=>void prepareLive()}>{livePreparing?'Preparando…':liveReady?'Preparar novamente':'Preparar LIVE'}</Button></>}/>
  {error&&<div className="data-error" role="alert"><span>{error}</span><button onClick={()=>location.reload()}>{t('Reload Studio')}</button></div>}
  <div className="broadcast-grid"><section className="broadcast-stage" aria-label={t('Final broadcast composition')}>
   <div className={`broadcast-frame broadcast-frame-${preset}`}><div className="broadcast-canvas-mount" ref={canvasMount}/>{preparing&&<div className="broadcast-loading"><Skeleton/></div>}{!preparing&&!hasMedia&&<div className="broadcast-placeholder"><Icon.VideoPlay/><b>{t('Your broadcast preview')}</b><span>{t('Add media to start composing the output.')}</span></div>}</div>
   <div className="broadcast-now"><span><Status label={t(state.status)} tone={statusTone(state.status)}/><b>{state.current?.name??t('No media selected')}</b></span><span><small>{t('Next')}</small><b>{state.next?.name??t('End of playlist')}</b></span></div>
   <div className="broadcast-controls"><input aria-label={t('Playback position')} disabled={!hasMedia} type="range" min="0" max={duration||0} step="0.1" value={Math.min(position,duration||0)} onChange={event=>{const value=Number(event.target.value);if(liveReady)void command('SEEK',{positionMs:value*1000},()=>engineRef.current?.seek(value));else engineRef.current?.seek(value)}}/><div><time>{formatTime(position)} <span>/ {formatTime(duration)}</span></time><div className="transport"><Control title={t('Previous')} disabled={!hasMedia} onClick={()=>liveReady?void command('PREVIOUS',{},()=>void engineRef.current?.previous()):void engineRef.current?.previous()}><Icon.ArrowUUpLeft/></Control><Control title={t('Stop')} disabled={!hasMedia} onClick={()=>liveReady?void command('STOP',{},()=>engineRef.current?.stop()):engineRef.current?.stop()}><Icon.Stop/></Control><Control primary title={t(isPlaying?'Pause':'Play')} disabled={!hasMedia} onClick={()=>liveReady?void command(isPlaying?'PAUSE':'PLAY',{},()=>isPlaying?engineRef.current?.pause():void engineRef.current?.play()):isPlaying?engineRef.current?.pause():void engineRef.current?.play()}>{isPlaying?<Icon.Pause/>:<Icon.Play/>}</Control><Control title={t('Next')} disabled={!hasMedia} onClick={()=>liveReady?void command('NEXT',{},()=>void engineRef.current?.next()):void engineRef.current?.next()}><Icon.SkipForward/></Control><Control active={state.loopPlaylist} title={t('Loop playlist')} onClick={()=>engineRef.current?.setLoopPlaylist(!state.loopPlaylist)}><Icon.ArrowClockwise/></Control><Control active={state.loopItem} title={t('Loop current item')} disabled={!hasMedia} onClick={()=>engineRef.current?.setLoopItem(!state.loopItem)}><Icon.ArrowsClockwise/></Control></div><label className="broadcast-volume"><button type="button" aria-label={t(state.muted?'Unmute':'Mute')} title={t(state.muted?'Unmute':'Mute')} onClick={()=>engineRef.current?.setMuted(!state.muted)}>{state.muted?<Icon.SpeakerSlash/>:<Icon.SpeakerHigh/>}</button><input aria-label={t('Volume')} type="range" min="0" max="1" step="0.05" value={liveReady?agent?.playback.volume??1:state.volume} onChange={event=>{const value=Number(event.target.value);if(liveReady)void command('SET_VOLUME',{volume:value},()=>engineRef.current?.setVolume(value));else engineRef.current?.setVolume(value)}}/></label></div></div>
  </section><aside className="broadcast-side"><Section title="Preparação da LIVE"><div className="live-preparation"><PrepRow label="Livefy Agent" value={agent?'Conectado':'Não encontrado'} ok={Boolean(agent)}/><PrepRow label="Livefy Camera" value={agent?.virtualCamera.installed&&agent.virtualCamera.registered?'Pronta':'Não instalada'} ok={Boolean(agent?.virtualCamera.installed&&agent.virtualCamera.registered)}/><PrepRow label="Vídeo" value={preparationLabel(preparation,agent)} ok={liveReady}/><PrepRow label="Saída" value={agent?.playback.state??'Aguardando'} ok={liveReady&&agent?.playback.state==='playing'}/><PrepRow label="TikTok Manager" value={extension?.tiktokDetected?'Detectado':'Aguardando'} ok={Boolean(extension?.tiktokDetected)}/>{liveReady&&<a className="button primary live-manager-link" href="https://shop.tiktok.com/streamer/live/product/dashboard" target="_blank" rel="noreferrer">Abrir TikTok LIVE Manager</a>}<div className="controller-panel-notice"><Icon.Browser/><span><b>Mantenha o controlador acessível</b><small>Use o painel lateral para acompanhar e controlar a sessão. Se fechá-lo, reabra pelo ícone da extensão; isso não inicia nem encerra uma LIVE pública.</small></span></div><small>A Livefy nunca inicia uma LIVE pública automaticamente.</small></div></Section><Section title={t('Output')}><label className="studio-field"><span>{t('Canvas preset')}</span><select value={preset} onChange={event=>choosePreset(event.target.value as BroadcastPreset)}><option value="vertical">1080 × 1920 · {t('Vertical')}</option><option value="horizontal">1920 × 1080 · {t('Horizontal')}</option><option value="square">1080 × 1080 · {t('Square')}</option></select></label><div className="output-health"><span><i className={state.videoTrack?'on':''}/>{t('Video track')}</span><span><i className={state.audioTrack?'on':''}/>{t('Audio track')}</span><span>{state.resolution.width} × {state.resolution.height} · {state.fps} FPS</span></div><details><summary>{t('Output stream validation')}</summary><video ref={debugVideo} className="broadcast-debug" autoPlay muted playsInline/></details></Section><Section title={t('Overlays')}><label className="studio-field"><span>{t('Featured product')}</span><select value={productId} onChange={event=>chooseProduct(event.target.value)}><option value="">{t('No product overlay')}</option>{products.map(product=><option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label className="studio-field"><span>{t('Headline')}</span><input value={text} placeholder={t('Optional text overlay')} onChange={event=>{setText(event.target.value);engineRef.current?.setText(event.target.value)}}/></label></Section></aside></div>
  <Section title={t('Playlist')} meta={<span>{state.items.length} {t(state.items.length===1?'item':'items')}</span>}><div className="broadcast-playlist">{loading||preparing?<Skeleton/>:state.items.length?state.items.map((item,index)=><div className={state.current?.id===item.id?'active':''} key={item.id}><button type="button" className="playlist-select" onClick={()=>void engineRef.current?.select(index)}><span>{state.current?.id===item.id?<Icon.SpeakerHigh/>:index+1}</span><span><b>{item.name}</b><small>{t(item.kind)} · {formatTime(item.duration_seconds)}</small></span></button><div><button type="button" aria-label={t('Move up')} title={t('Move up')} disabled={index===0} onClick={()=>move(index,-1)}><Icon.CaretUpDown/></button><button type="button" aria-label={t('Move down')} title={t('Move down')} disabled={index===state.items.length-1} onClick={()=>move(index,1)}><Icon.CaretDown/></button><button type="button" aria-label={t('Remove from playlist')} title={t('Remove from playlist')} onClick={()=>void remove(index)}><Icon.X/></button></div></div>):<div className="empty-state broadcast-empty"><div className="empty-icon"><Icon.PlayCircle/></div><h3>{t('No media in the playlist')}</h3><p>{t('Upload videos on the Media page, then return here to start the browser broadcast.')}</p><Button kind="primary" onClick={()=>{location.hash='media'}}>{t('Open Media')}</Button></div>}</div></Section>
 </div>;
}

function Control({title,children,onClick,disabled=false,active=false,primary=false}:{title:string;children:ReactNode;onClick:()=>void;disabled?:boolean;active?:boolean;primary?:boolean}){return <button type="button" aria-label={title} title={title} disabled={disabled} className={`${primary?'transport-primary ':''}${active?'active':''}`} onClick={onClick}>{children}</button>}
function PrepRow({label,value,ok}:{label:string;value:string;ok:boolean}){return <div className="prep-row"><span><i className={ok?'on':''}/>{label}</span><b>{value}</b></div>}
function preparationLabel(state:PreparationState,agent:AgentDiagnostics|null){const labels:Record<PreparationState,string>={idle:'Aguardando',checking_camera:'Verificando câmera',preparing_media:'Validando mídia',downloading:`Baixando ${agent?.preparation.mediaPrepared??0}/${agent?.preparation.mediaTotal??0}`,loading:'Carregando playlist',ready:'Preparado',error:'Falha'};return labels[state]}
function isAgentUnavailableError(message:string){return /^Livefy Agent não encontrado\./.test(message)}
function friendlyError(failure:unknown){const message=failure instanceof Error?failure.message:String(failure);if(/not found|offline|timed out/i.test(message))return'Livefy Agent não encontrado. Instale ou reinicie o Agent e tente novamente.';if(/camera.*not installed|registered/i.test(message))return'A Livefy Camera não está instalada corretamente. Use Reparar câmera e reinicie o Chrome.';if(/expired|403|401/i.test(message))return'O acesso temporário ao vídeo expirou. Clique em Preparar LIVE novamente.';if(/disk space/i.test(message))return'Não há espaço suficiente no disco para preparar este vídeo.';if(/ffprobe|invalid media/i.test(message))return'O arquivo de vídeo é inválido ou não pôde ser analisado.';return message}
async function resolveMedia(items:MediaItem[]):Promise<ResolvedMedia[]>{return Promise.all(items.map(async item=>{const signed=await supabase.storage.from('media').createSignedUrl(item.storage_path,3600);if(signed.error)throw signed.error;return{...item,kind:mediaKind(item.name),url:signed.data.signedUrl,urlExpiresAt:Date.now()+55*60_000}}))}
