import { useEffect,useRef,useState } from 'react';
import * as Icon from '../../icons';import { Button,PageHeader,Section,Skeleton,Status } from '../../components';import { useLivefyData,type MediaItem } from '../../livefy-data';import { supabase } from '../../lib/supabase';import { BroadcastEngine } from '../../broadcast/broadcast-engine';import { DebugDestination } from '../../broadcast/destination';import { mediaKind,type BroadcastPreset,type BroadcastState,type ResolvedMedia } from '../../broadcast/types';

const emptyState:BroadcastState={status:'idle',current:null,next:null,currentTime:0,duration:0,volume:1,muted:false,loopPlaylist:true,loopItem:false,resolution:{width:1080,height:1920},fps:30,videoTrack:false,audioTrack:false,errors:[]};
const formatTime=(value:number)=>{const safe=Number.isFinite(value)?Math.max(value,0):0;return`${Math.floor(safe/60).toString().padStart(2,'0')}:${Math.floor(safe%60).toString().padStart(2,'0')}`};

export default function BroadcastStudio(){
 const{media,products,workspace,loading,refresh}=useLivefyData();const canvasHost=useRef<HTMLDivElement>(null);const debugVideo=useRef<HTMLVideoElement>(null);const engineRef=useRef<BroadcastEngine|null>(null);const[state,setState]=useState(emptyState);const[preparing,setPreparing]=useState(true);const[error,setError]=useState('');const[preset,setPreset]=useState<BroadcastPreset>('vertical');const[productId,setProductId]=useState('');const[text,setText]=useState('');
 useEffect(()=>{let alive=true;const engine=new BroadcastEngine();engineRef.current=engine;const offState=engine.events.on('state',setState);const offError=engine.events.on('error',failure=>setError(failure.message));const offDuration=engine.events.on('media:duration',({id,duration})=>{void supabase.from('media_items').update({duration_seconds:duration}).eq('id',id)});
  let renewal=0;const start=async()=>{try{const resolved=await resolveMedia(media);if(!alive)return;await engine.initialize(resolved);if(canvasHost.current){canvasHost.current.append(engine.composer.canvas);engine.composer.canvas.className='broadcast-canvas'}if(debugVideo.current)await engine.attachDestination(new DebugDestination(debugVideo.current));renewal=window.setInterval(()=>void resolveMedia(media).then(items=>engine.playlist.load(items)).catch(failure=>setError(failure instanceof Error?failure.message:'Signed media URLs could not be renewed.')),50*60_000)}catch(failure){setError(failure instanceof Error?failure.message:'Could not initialize Broadcast Core.')}finally{if(alive)setPreparing(false)}};void start();return()=>{alive=false;clearInterval(renewal);engine.composer.canvas.remove();offState();offError();offDuration();void engine.destroy();engineRef.current=null}},[media]);
 const persistOrder=async(items:ResolvedMedia[])=>{await Promise.all(items.map((item,position)=>supabase.from('media_items').update({position}).eq('id',item.id)));await refresh()};
 const move=(index:number,direction:-1|1)=>{const engine=engineRef.current;if(!engine)return;const target=index+direction;engine.playlist.reorder(index,target);void persistOrder(engine.playlist.snapshot.items)};
 const remove=async(index:number)=>{const engine=engineRef.current;if(!engine)return;const id=engine.playlist.snapshot.items[index]?.id;engine.playlist.remove(index);if(id)await supabase.from('media_items').delete().eq('id',id);await refresh()};
 const selectProduct=(id:string)=>{setProductId(id);engineRef.current?.setProduct(products.find(product=>product.id===id)??null)};
 const selectPreset=(value:BroadcastPreset)=>{setPreset(value);engineRef.current?.setPreset(value)};
 return <div className="page wide broadcast-studio"><PageHeader eyebrow="Broadcast Core" title="Studio" description="Compose and play your private media as a browser-generated audiovisual stream." actions={<><Status label={state.videoTrack&&state.audioTrack?'Output stream ready':'Preparing output'} tone={state.videoTrack&&state.audioTrack?'online':'warning'}/><Button kind="primary" icon={<Icon.Play/>} disabled={preparing||!state.current} onClick={()=>void engineRef.current?.play()}>Play output</Button></>}/>
  {error&&<div className="data-error" role="alert">{error}<button onClick={()=>location.reload()}>Reload Studio</button></div>}
  <div className="broadcast-grid"><section className="broadcast-stage" aria-label="Final broadcast composition"><div className={`broadcast-frame broadcast-frame-${preset}`} ref={canvasHost}>{preparing&&<div className="broadcast-loading"><Skeleton/></div>}</div><div className="broadcast-now"><span><Status label={state.status} tone={state.status==='playing'?'online':state.status==='error'?'error':state.status==='paused'?'paused':'neutral'}/><b>{state.current?.name??'No media selected'}</b></span><span><small>Next</small><b>{state.next?.name??'End of playlist'}</b></span></div>
   <div className="broadcast-controls"><input aria-label="Playback position" type="range" min="0" max={state.duration||0} step="0.1" value={Math.min(state.currentTime,state.duration||0)} onChange={event=>engineRef.current?.seek(Number(event.target.value))}/><div><time>{formatTime(state.currentTime)} <span>/ {formatTime(state.duration)}</span></time><div className="transport"><button title="Previous" onClick={()=>void engineRef.current?.previous()}><Icon.ArrowUUpLeft/></button><button title="Stop" onClick={()=>engineRef.current?.stop()}><Icon.Stop/></button><button className="transport-primary" title={state.status==='playing'?'Pause':'Play'} onClick={()=>state.status==='playing'?engineRef.current?.pause():void engineRef.current?.play()}>{state.status==='playing'?<Icon.Pause/>:<Icon.Play/>}</button><button title="Next" onClick={()=>void engineRef.current?.next()}><Icon.SkipForward/></button><button className={state.loopPlaylist?'active':''} title="Loop playlist" onClick={()=>engineRef.current?.setLoopPlaylist(!state.loopPlaylist)}><Icon.ArrowClockwise/></button></div><label className="broadcast-volume"><button title={state.muted?'Unmute':'Mute'} onClick={()=>engineRef.current?.setMuted(!state.muted)}>{state.muted?<Icon.EyeSlash/>:<Icon.SpeakerHigh/>}</button><input aria-label="Volume" type="range" min="0" max="1" step="0.05" value={state.volume} onChange={event=>engineRef.current?.setVolume(Number(event.target.value))}/></label></div></div>
  </section>
  <aside className="broadcast-side"><Section title="Output"><label className="studio-field"><span>Canvas preset</span><select value={preset} onChange={event=>selectPreset(event.target.value as BroadcastPreset)}><option value="vertical">1080 × 1920 · Vertical</option><option value="horizontal">1920 × 1080 · Horizontal</option><option value="square">1080 × 1080 · Square</option></select></label><div className="output-health"><span><i className={state.videoTrack?'on':''}/>Video track</span><span><i className={state.audioTrack?'on':''}/>Audio track</span><span>{state.resolution.width} × {state.resolution.height} · {state.fps} FPS</span></div><details><summary>MediaStream debug proof</summary><video ref={debugVideo} className="broadcast-debug" autoPlay muted playsInline/></details></Section>
   <Section title="Overlays"><label className="studio-field"><span>Featured product</span><select value={productId} onChange={event=>selectProduct(event.target.value)}><option value="">No product overlay</option>{products.map(product=><option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label className="studio-field"><span>Headline</span><input value={text} placeholder="Optional text overlay" onChange={event=>{setText(event.target.value);engineRef.current?.setText(event.target.value)}}/></label></Section>
  </aside></div>
  <Section title="Playlist" meta={<span>{state.current?`${state.items?.length??media.length} items`: `${media.length} items`}</span>}><div className="broadcast-playlist">{loading||preparing?<Skeleton/>:state.current?engineRef.current?.playlist.snapshot.items.map((item,index)=><div className={state.current?.id===item.id?'active':''} key={item.id}><button className="playlist-select" onClick={()=>void engineRef.current?.select(index)}><span>{state.current?.id===item.id?<Icon.SpeakerHigh/>:index+1}</span><span><b>{item.name}</b><small>{item.kind} · {formatTime(item.duration_seconds)}</small></span></button><div><button title="Move up" disabled={index===0} onClick={()=>move(index,-1)}><Icon.CaretUpDown/></button><button title="Move down" disabled={index===engineRef.current!.playlist.snapshot.items.length-1} onClick={()=>move(index,1)}><Icon.CaretDown/></button><button title="Remove from playlist" onClick={()=>void remove(index)}><Icon.X/></button></div></div>):<div className="empty-state"><div className="empty-icon"><Icon.PlayCircle/></div><h3>No media in the playlist</h3><p>Upload videos on the Media page, then return here to start the browser broadcast.</p><Button kind="primary" onClick={()=>{location.hash='media'}}>Open Media</Button></div>}</div></Section>
 </div>;
}

async function resolveMedia(items:MediaItem[]):Promise<ResolvedMedia[]>{return Promise.all(items.map(async item=>{const signed=await supabase.storage.from('media').createSignedUrl(item.storage_path,3600);if(signed.error)throw signed.error;return{...item,kind:mediaKind(item.name),url:signed.data.signedUrl,urlExpiresAt:Date.now()+55*60_000}}))}
