import { useEffect,useRef,useState,type ReactNode } from 'react';
import * as Icon from '../../icons';
import { Button,PageHeader,Section,Skeleton,Status } from '../../components';
import { useI18n } from '../../i18n';
import { useLivefyData,type MediaItem } from '../../livefy-data';
import { supabase } from '../../lib/supabase';
import { BroadcastEngine } from '../../broadcast/broadcast-engine';
import { DebugDestination } from '../../broadcast/destination';
import { mediaKind,type BroadcastPreset,type BroadcastState,type ResolvedMedia,type RuntimeStatus } from '../../broadcast/types';

const initialState:BroadcastState={items:[],status:'idle',current:null,next:null,currentTime:0,duration:0,volume:1,muted:false,loopPlaylist:true,loopItem:false,resolution:{width:1080,height:1920},fps:30,videoTrack:false,audioTrack:false,errors:[]};
const formatTime=(value:number)=>{const safe=Number.isFinite(value)?Math.max(value,0):0;return`${String(Math.floor(safe/60)).padStart(2,'0')}:${String(Math.floor(safe%60)).padStart(2,'0')}`};
const statusTone=(status:RuntimeStatus)=>status==='playing'?'online':status==='error'?'error':status==='paused'?'paused':'neutral';

export default function BroadcastStudio(){
 const{media,products,loading,refresh}=useLivefyData();const{t}=useI18n();
 const canvasMount=useRef<HTMLDivElement>(null);const debugVideo=useRef<HTMLVideoElement>(null);const engineRef=useRef<BroadcastEngine|null>(null);
 const[state,setState]=useState(initialState);const[preparing,setPreparing]=useState(true);const[error,setError]=useState('');const[preset,setPreset]=useState<BroadcastPreset>('vertical');const[productId,setProductId]=useState('');const[text,setText]=useState('');
 useEffect(()=>{let alive=true;let renewal=0;const engine=new BroadcastEngine();engineRef.current=engine;const offState=engine.events.on('state',setState);const offError=engine.events.on('error',failure=>setError(failure.message));const offDuration=engine.events.on('media:duration',({id,duration})=>{void supabase.from('media_items').update({duration_seconds:duration}).eq('id',id)});
  const start=async()=>{try{const resolved=await resolveMedia(media);if(!alive)return;await engine.initialize(resolved);engine.composer.canvas.className='broadcast-canvas';canvasMount.current?.append(engine.composer.canvas);if(debugVideo.current)await engine.attachDestination(new DebugDestination(debugVideo.current));renewal=window.setInterval(()=>void resolveMedia(media).then(items=>engine.playlist.load(items)).catch(failure=>setError(failure instanceof Error?failure.message:t('Signed media URLs could not be renewed.'))),50*60_000)}catch(failure){setError(failure instanceof Error?failure.message:t('Could not initialize Broadcast Core.'))}finally{if(alive)setPreparing(false)}};void start();return()=>{alive=false;clearInterval(renewal);engine.composer.canvas.remove();offState();offError();offDuration();void engine.destroy();engineRef.current=null}},[media,t]);
 const persistOrder=async(items:ResolvedMedia[])=>{const results=await Promise.all(items.map((item,position)=>supabase.from('media_items').update({position}).eq('id',item.id)));const failure=results.find(result=>result.error)?.error;if(failure)setError(failure.message)};
 const move=(index:number,direction:-1|1)=>{const engine=engineRef.current;if(!engine)return;engine.playlist.reorder(index,index+direction);void persistOrder(engine.playlist.snapshot.items)};
 const remove=async(index:number)=>{const engine=engineRef.current,item=state.items[index];if(!engine||!item)return;engine.playlist.remove(index);const result=await supabase.from('media_items').update({status:'archived'}).eq('id',item.id);if(result.error){setError(result.error.message);await refresh()}else await persistOrder(engine.playlist.snapshot.items)};
 const chooseProduct=(id:string)=>{setProductId(id);engineRef.current?.setProduct(products.find(product=>product.id===id)??null)};const choosePreset=(value:BroadcastPreset)=>{setPreset(value);engineRef.current?.setPreset(value)};const hasMedia=Boolean(state.current),isPlaying=state.status==='playing';
 return <div className="page wide broadcast-studio">
  <PageHeader eyebrow={t('Broadcast Core')} title={t('Broadcast Studio')} description={t('Compose and play private media as a browser-generated audiovisual stream.')} actions={<><Status label={t(state.videoTrack&&state.audioTrack?'Output stream ready':'Preparing output')} tone={state.videoTrack&&state.audioTrack?'online':'warning'}/><Button kind="primary" icon={<Icon.Play/>} disabled={preparing||!hasMedia} onClick={()=>void engineRef.current?.play()}>{t('Play output')}</Button></>}/>
  {error&&<div className="data-error" role="alert"><span>{error}</span><button onClick={()=>location.reload()}>{t('Reload Studio')}</button></div>}
  <div className="broadcast-grid"><section className="broadcast-stage" aria-label={t('Final broadcast composition')}>
   <div className={`broadcast-frame broadcast-frame-${preset}`}><div className="broadcast-canvas-mount" ref={canvasMount}/>{preparing&&<div className="broadcast-loading"><Skeleton/></div>}{!preparing&&!hasMedia&&<div className="broadcast-placeholder"><Icon.VideoPlay/><b>{t('Your broadcast preview')}</b><span>{t('Add media to start composing the output.')}</span></div>}</div>
   <div className="broadcast-now"><span><Status label={t(state.status)} tone={statusTone(state.status)}/><b>{state.current?.name??t('No media selected')}</b></span><span><small>{t('Next')}</small><b>{state.next?.name??t('End of playlist')}</b></span></div>
   <div className="broadcast-controls"><input aria-label={t('Playback position')} disabled={!hasMedia} type="range" min="0" max={state.duration||0} step="0.1" value={Math.min(state.currentTime,state.duration||0)} onChange={event=>engineRef.current?.seek(Number(event.target.value))}/><div><time>{formatTime(state.currentTime)} <span>/ {formatTime(state.duration)}</span></time><div className="transport"><Control title={t('Previous')} disabled={!hasMedia} onClick={()=>void engineRef.current?.previous()}><Icon.ArrowUUpLeft/></Control><Control title={t('Stop')} disabled={!hasMedia} onClick={()=>engineRef.current?.stop()}><Icon.Stop/></Control><Control primary title={t(isPlaying?'Pause':'Play')} disabled={!hasMedia} onClick={()=>isPlaying?engineRef.current?.pause():void engineRef.current?.play()}>{isPlaying?<Icon.Pause/>:<Icon.Play/>}</Control><Control title={t('Next')} disabled={!hasMedia} onClick={()=>void engineRef.current?.next()}><Icon.SkipForward/></Control><Control active={state.loopPlaylist} title={t('Loop playlist')} onClick={()=>engineRef.current?.setLoopPlaylist(!state.loopPlaylist)}><Icon.ArrowClockwise/></Control><Control active={state.loopItem} title={t('Loop current item')} disabled={!hasMedia} onClick={()=>engineRef.current?.setLoopItem(!state.loopItem)}><Icon.ArrowsClockwise/></Control></div><label className="broadcast-volume"><button type="button" aria-label={t(state.muted?'Unmute':'Mute')} title={t(state.muted?'Unmute':'Mute')} onClick={()=>engineRef.current?.setMuted(!state.muted)}>{state.muted?<Icon.SpeakerSlash/>:<Icon.SpeakerHigh/>}</button><input aria-label={t('Volume')} type="range" min="0" max="1" step="0.05" value={state.volume} onChange={event=>engineRef.current?.setVolume(Number(event.target.value))}/></label></div></div>
  </section><aside className="broadcast-side"><Section title={t('Output')}><label className="studio-field"><span>{t('Canvas preset')}</span><select value={preset} onChange={event=>choosePreset(event.target.value as BroadcastPreset)}><option value="vertical">1080 × 1920 · {t('Vertical')}</option><option value="horizontal">1920 × 1080 · {t('Horizontal')}</option><option value="square">1080 × 1080 · {t('Square')}</option></select></label><div className="output-health"><span><i className={state.videoTrack?'on':''}/>{t('Video track')}</span><span><i className={state.audioTrack?'on':''}/>{t('Audio track')}</span><span>{state.resolution.width} × {state.resolution.height} · {state.fps} FPS</span></div><details><summary>{t('Output stream validation')}</summary><video ref={debugVideo} className="broadcast-debug" autoPlay muted playsInline/></details></Section><Section title={t('Overlays')}><label className="studio-field"><span>{t('Featured product')}</span><select value={productId} onChange={event=>chooseProduct(event.target.value)}><option value="">{t('No product overlay')}</option>{products.map(product=><option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label className="studio-field"><span>{t('Headline')}</span><input value={text} placeholder={t('Optional text overlay')} onChange={event=>{setText(event.target.value);engineRef.current?.setText(event.target.value)}}/></label></Section></aside></div>
  <Section title={t('Playlist')} meta={<span>{state.items.length} {t(state.items.length===1?'item':'items')}</span>}><div className="broadcast-playlist">{loading||preparing?<Skeleton/>:state.items.length?state.items.map((item,index)=><div className={state.current?.id===item.id?'active':''} key={item.id}><button type="button" className="playlist-select" onClick={()=>void engineRef.current?.select(index)}><span>{state.current?.id===item.id?<Icon.SpeakerHigh/>:index+1}</span><span><b>{item.name}</b><small>{t(item.kind)} · {formatTime(item.duration_seconds)}</small></span></button><div><button type="button" aria-label={t('Move up')} title={t('Move up')} disabled={index===0} onClick={()=>move(index,-1)}><Icon.CaretUpDown/></button><button type="button" aria-label={t('Move down')} title={t('Move down')} disabled={index===state.items.length-1} onClick={()=>move(index,1)}><Icon.CaretDown/></button><button type="button" aria-label={t('Remove from playlist')} title={t('Remove from playlist')} onClick={()=>void remove(index)}><Icon.X/></button></div></div>):<div className="empty-state"><div className="empty-icon"><Icon.PlayCircle/></div><h3>{t('No media in the playlist')}</h3><p>{t('Upload videos on the Media page, then return here to start the browser broadcast.')}</p><Button kind="primary" onClick={()=>{location.hash='media'}}>{t('Open Media')}</Button></div>}</div></Section>
 </div>;
}

function Control({title,children,onClick,disabled=false,active=false,primary=false}:{title:string;children:ReactNode;onClick:()=>void;disabled?:boolean;active?:boolean;primary?:boolean}){return <button type="button" aria-label={title} title={title} disabled={disabled} className={`${primary?'transport-primary ':''}${active?'active':''}`} onClick={onClick}>{children}</button>}
async function resolveMedia(items:MediaItem[]):Promise<ResolvedMedia[]>{return Promise.all(items.map(async item=>{const signed=await supabase.storage.from('media').createSignedUrl(item.storage_path,3600);if(signed.error)throw signed.error;return{...item,kind:mediaKind(item.name),url:signed.data.signedUrl,urlExpiresAt:Date.now()+55*60_000}}))}
